DROP DATABASE IF EXISTS `kouka_db`;
CREATE DATABASE `kouka_db`;
USE `kouka_db`;
DROP TABLE IF EXISTS `PRODUCT`;

CREATE TABLE `PRODUCT`(
	`id` INT(5) AUTO_INCREMENT PRIMARY KEY, 
	`name` VARCHAR(100) NOT NULL, 
	`storage` VARCHAR(100) NOT NULL, 
	`description` VARCHAR(100) NOT NULL,
	`usage` VARCHAR(100) NOT NULL,
	`note` VARCHAR(100) NOT NULL
) DEFAULT CHARSET = utf8;